#!/usr/bin/bash
monitor=`hyprctl monitors | grep Monitor | awk '{print $2}'`

wpDir="$HOME/Wallpapers/Rose_Pine/"

#wpFile=$(find "$wpDir" -type f -name "*.jpg" -o -name "*.jpeg" -o -name "*.png" -o -name "*.gif" | shuf -n 1)
wpFile=$wpDir/squiggly.png
cp $wpFile ~/.cache/wp.png
hyprctl hyprpaper unload all
hyprctl hyprpaper preload $wpFile
hyprctl hyprpaper wallpaper "$monitor, $wpFile"
